// A finite practice path: never cycle back to a question already asked.
export const demoQuestions: Record<string, string[]> = {
  animals: [
    "What can your favorite animal do?",
    "What does it eat?",
    "Where does it live?",
    "How would you describe the way it looks?",
    "How is it different from a cat?",
    "Imagine you could be an animal for a day. What would you do?",
    "How can people help wild animals?",
    "What would you like to learn about another animal?",
  ],
  "my-town": [
    "What can you do in a park?",
    "Would you rather visit a library or a playground?",
    "What would make an imaginary town fun?",
    "How could people travel around that town?",
    "What would you put beside its library?",
    "What could visitors do on a rainy day?",
    "How could people keep that town clean?",
    "What would you add to make it better?",
  ],
  "daily-routines": [
    "What do you do before going to bed?",
    "How is your weekend different?",
    "What part of the day do you enjoy most?",
    "What do you do when you have extra free time?",
    "What helps you get ready in the morning?",
    "What did you do after breakfast yesterday?",
    "What would you change about your routine?",
    "What would your perfect day be like?",
  ],
  hobbies: [
    "What do you need for your favorite hobby?",
    "How did you first try it?",
    "What is the hardest part?",
    "What would you teach a beginner?",
    "Would you rather try dancing or painting?",
    "What new hobby would you like to try?",
    "How could you practice on a rainy day?",
    "What would you like to make or learn next?",
  ],
  food: [
    "What does your favorite food taste like?",
    "Would you rather eat something sweet or salty?",
    "What fruit would you put in a fruit salad?",
    "What would you make for an imaginary picnic?",
    "How would you describe a food you dislike?",
    "What new food would you like to try?",
    "What would you serve in your own restaurant?",
    "How would you make a simple sandwich?",
  ],
  family: [
    "What is a fun activity people can do together indoors?",
    "What could a family do on a rainy afternoon?",
    "How can you help someone at home?",
    "What would you take to a picnic together?",
    "What kind of film is fun to watch together?",
    "How could you teach someone a new game?",
    "What makes someone a good listener?",
    "What activity would you like to try together?",
  ],
  school: [
    "What is something interesting you learned recently?",
    "What would you put in an imaginary classroom?",
    "Would you rather draw a picture or do an experiment?",
    "How can students help each other learn?",
    "What makes a lesson interesting?",
    "What would you teach if you were the teacher?",
    "What would you invent for a school project?",
    "What would you like to learn next?",
  ],
  holiday: [
    "How would you travel on an imaginary holiday?",
    "What would you do on the first morning?",
    "What would you do if it rained?",
    "What food would you like to try?",
    "Would you rather go camping or stay in a hotel?",
    "What would you take a picture of?",
    "How would you describe your perfect holiday?",
    "What would you tell a friend about that adventure?",
  ],
  feelings: [
    "What is something you look forward to?",
    "How can music change a person's mood?",
    "What could you say to encourage a friend?",
    "What does an excited character in a story look like?",
    "What helps you rest after a busy day?",
    "What small thing can make a day better?",
    "How might someone feel before trying a new hobby?",
    "What would make a story character feel proud?",
  ],
  home: [
    "What colors would you choose for your dream room?",
    "Where would you put a comfortable chair?",
    "What could you see from an imaginary window?",
    "What would make a room good for reading?",
    "Would you rather have a garden or a balcony?",
    "What would you grow in an imaginary garden?",
    "How could you make a small room feel cozy?",
    "What would you invent to help around the home?",
  ],
};
